# Generated by Django 5.2.2 on 2025-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.URLField()),
                ('song_name', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=10)),
                ('lyrics', models.TextField()),
                ('release_date', models.DateField()),
                ('producer', models.CharField(max_length=30)),
                ('song_url', models.URLField()),
            ],
        ),
    ]
