# Generated by Django 5.2.2 on 2025-06-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_alter_music_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='music.music')),
            ],
        ),
    ]
