# Generated by Django 5.2.2 on 2025-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_release_date'),
        ('playlist', '0002_remove_playlist_music_id_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music.music'),
        ),
    ]
