# Generated by Django 5.2.2 on 2025-06-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_playlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='owner',
        ),
    ]
